collections:
  projects:
    output: true

  artists:
    output: true

defaults:
  - scope:
      path: ""
      type: "artists"
    values:
      layout: "artist"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
